name: extract-xz-files

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  extract:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: free disk space
        run: |
          rm -rf /home/runner/work/btfhub-archive/btfhub-archive
          sudo mkdir -p /mnt/btfhub-archive
          sudo chown $(id -u) /mnt/btfhub-archive
          sudo ln -s /mnt/btfhub-archive /home/runner/work/btfhub-archive/btfhub-archive
          rm -rf /opt/hostedtoolcache
          df -lh

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        #with:
          # path: '../../../../../mnt/btfhub-archive'

      # Runs a single command using the runners shell
      - name: extract xz files
        run: |
          find . -type d -print0 | while IFS= read -r -d $'\0' dir; do
            find "$dir" -type f -name "*.tar.xz" | while IFS= read -r file; do
              echo "$file"
              dir_path=$(dirname "$file")
              tar -xvf "$file" -C "$dir_path"
            done
          done

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "extract new xz files"

      - name: Push changes
        run: |
          git push
